name: Client Side Tools and Coverage

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Send Client Side Tools and Coverage Results - 
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          export CODACY_CODE=$GITHUB_WORKSPACE
          sudo apt-get -qq update
          sudo apt-get -y -qq install openjdk-8-jdk openjdk-8-jre
          pip3 install coverage
          pip3 install pytest
          coverage run -m pytest -m unittest /home/runner/work/sample-python-project/sample-python-project/*.py
          coverage report /home/runner/work/sample-python-project/sample-python-project/*.py
          coverage xml
          echo $?
